<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="style.css" type="text/css">
</head>
<p id="notifier">notifications go here</p>
<canvas id="DrawArea" width="600" height="400"></canvas>
<br>
<button type="button" onclick="toggleAction()">pause/play</button>

<button type="button" onclick="clearGrids()">reset grid</button>

<button type="button" onclick="step()">step</button>

<button type="button" onclick="saveGrid()">convert</button>

<button type="button" onclick="loadGrid()">load</button>
<br>
<textarea id="display" rows="30" cols="90"></textarea>

<br>

<script type ="text/javascript" src="game-of-life.js"></script>
