<!DOCTYPE html>
<html>

<head>
	<title>Javascrip Game of Life</title>
	<link rel="stylesheet" href="style.css" type="text/css">
	<link rel="icon" href="GoL.gif">
	<script type="text/javascript" defer="defer" src="game-of-life.js"></script>
	<script type="text/javascript" defer="defer" src="convert.js"></script>
</head>

<body>
<p id="notifier">notifications go here</p>
<div class="border" id="canvasArea">
	<canvas id="backGround" class="cnvs" width="600" height="400"></canvas>
	<canvas id="DrawArea" class="cnvs" width="600" height="400"></canvas>
</div>

<div class="border" id="buttonArea">
	<button type="button" onclick="toggleAction()">pause/play</button>

	<button type="button" onclick="clearGrids()">reset grid</button>

	<button type="button" onclick="step()">step</button>

	<button type="button" onclick="saveGrid()">convert</button>

	<button type="button" onclick="loadGrid()">load</button>

	<button type="button" onclick="transformGrid()">transform</button>
</div>

<div class="border" id="loadArea">
	<textarea id="display" rows="59" cols="84"></textarea>
</div>


</body>

</html>

