<!DOCTYPE html>
<html>

<head>
	<title>Javascrip Game of Life</title>
	<link rel="stylesheet" href="style.css" type="text/css">
	<link rel="icon" href="GoL.gif">
</head>

<body>
<p id="notifier">notifications go here</p>
<div class="border" id="canvasArea">
	<canvas id="DrawArea" width="600" height="400"></canvas>
</div>

<div class="border" id="buttonArea">
	<button type="button" onclick="toggleAction()">pause/play</button>

	<button type="button" onclick="clearGrids()">reset grid</button>

	<button type="button" onclick="step()">step</button>

	<button type="button" onclick="saveGrid()">convert</button>

	<button type="button" onclick="loadGrid()">load</button>
</div>

<div class="border" id="loadArea">
	<textarea id="display" rows="30" cols="90"></textarea>
</div>


</body>

<script type ="text/javascript" src="game-of-life.js"></script>
